// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// forwardAlgorithmCpp
NumericMatrix forwardAlgorithmCpp(NumericMatrix& e, NumericMatrix& t, NumericVector& prior);
RcppExport SEXP flexHMM_forwardAlgorithmCpp(SEXP eSEXP, SEXP tSEXP, SEXP priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type e(eSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type prior(priorSEXP);
    rcpp_result_gen = Rcpp::wrap(forwardAlgorithmCpp(e, t, prior));
    return rcpp_result_gen;
END_RCPP
}
// backwardAlgorithmCpp
NumericMatrix backwardAlgorithmCpp(NumericMatrix& e, NumericMatrix& t);
RcppExport SEXP flexHMM_backwardAlgorithmCpp(SEXP eSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type e(eSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(backwardAlgorithmCpp(e, t));
    return rcpp_result_gen;
END_RCPP
}
