# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

forwardAlgorithmCpp <- function(e, t, prior) {
    .Call('flexHMM_forwardAlgorithmCpp', PACKAGE = 'flexHMM', e, t, prior)
}

backwardAlgorithmCpp <- function(e, t) {
    .Call('flexHMM_backwardAlgorithmCpp', PACKAGE = 'flexHMM', e, t)
}

