# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

forwardAlgorithmCpp <- function(e, t, prior) {
    .Call('_flexHMM_forwardAlgorithmCpp', PACKAGE = 'flexHMM', e, t, prior)
}

forwardAlgorithmSparseCpp <- function(e, t, prior, permTrans, tLen) {
    .Call('_flexHMM_forwardAlgorithmSparseCpp', PACKAGE = 'flexHMM', e, t, prior, permTrans, tLen)
}

backwardAlgorithmCpp <- function(e, t) {
    .Call('_flexHMM_backwardAlgorithmCpp', PACKAGE = 'flexHMM', e, t)
}

backwardAlgorithmSparseCpp <- function(e, t, permTrans, tLen) {
    .Call('_flexHMM_backwardAlgorithmSparseCpp', PACKAGE = 'flexHMM', e, t, permTrans, tLen)
}

computeMarginalProbabilityCpp <- function(alpha, beta) {
    .Call('_flexHMM_computeMarginalProbabilityCpp', PACKAGE = 'flexHMM', alpha, beta)
}

computeViterbiPathCpp <- function(alpha, trans) {
    .Call('_flexHMM_computeViterbiPathCpp', PACKAGE = 'flexHMM', alpha, trans)
}

